name: loginform
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.8.0
  shared_preferences: ^2.3.3
  intl: ^0.20.2
  provider: ^6.1.5
  timezone: ^0.10.1
  flutter_timezone: ^4.1.1
  cupertino_icons: ^1.0.8
  flutter_local_notifications: ^19.3.0
  uuid: ^4.5.1
  geolocator: ^13.0.2
  http: ^1.4.0
  audioplayers: ^6.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
assets:
    - assets/sounds/
    - assets/images/weather/